name: Build Windows exe


on:
push:
branches: [ main, master ]
workflow_dispatch: {}


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4


- name: Setup Go
uses: actions/setup-go@v5
with:
go-version: '1.22.x'


- name: Tidy
run: go mod tidy


- name: Build Windows amd64
run: |
GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o tsnet-browser-proxy.exe ./main.go


- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: tsnet-browser-proxy-windows-amd64
path: tsnet-browser-proxy.exe
